version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: filesmate-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: filesmate
      POSTGRES_USER: filesmate
      POSTGRES_PASSWORD: filesmate
    ports:
      - "5432:5432"
    volumes:
      - filesmate:/var/lib/postgresql/data
    networks:
      - filesmate-net

volumes:
  filesmate:

networks:
  filesmate-net:
    driver: bridge
