version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: filemate-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: filemate
      POSTGRES_USER: filemate
      POSTGRES_PASSWORD: filemate
    ports:
      - "5432:5432"
    volumes:
      - filemate:/var/lib/postgresql/data
    networks:
      - filemate-net

volumes:
  filemate:

networks:
  filemate-net:
    driver: bridge
